### ISSUE TITLE
IRepository<T> is synchronous 

### ISSUE THREAD

**Issue by yeirg** [irgayer/Crapper#1]
Rewrite interface and implementation to async.

**Comment by Developing-Developer2019** [comment]
Hi bud, trying to push do a pull request into your repo for this issue but you don't have a contributing.md file

https://github.com/github/docs/blob/main/CONTRIBUTING.md - for information on adding one

Opened an issue here: https://github.com/irgayer/Crapper/issues/2

**Comment by yeirg** [comment]
IRepository<T> is async now.
