### ISSUE TITLE
Add contributing.md file to repository to allow people to contribute when you have issues/tickets

### ISSUE THREAD

**Issue by Developing-Developer2019** [irgayer/Crapper#2]
https://github.com/github/docs/blob/main/CONTRIBUTING.md - for reference

**Comment by yeirg** [comment]
> https://github.com/github/docs/blob/main/CONTRIBUTING.md - for reference

Am I doing right 🤡 ? @Developing-Developer2019

**Comment by Developing-Developer2019** [comment]
Brilliant, looks good

**Comment by yeirg** [comment]
Thanks
