### ISSUE TITLE
Add CancellationToken

### ISSUE THREAD

**Issue by yeirg** [irgayer/Crapper#6]
Add CancellationToken where possible and required for proper execution (?)

**Comment by Developing-Developer2019** [comment]
CancellationTokens are added in your Modelstores, which then you would add in the calling methods: I.E:

public async Task<IdentityResult> CreateAsync(ApplicationUser user, CancellationToken cancellationToken)
{
    cancellationToken.ThrowIfCancellationRequested();
// Create user

return IdentityResult.Success
}
