### ISSUE TITLE
Unable to run your APIs due to JWT

### ISSUE THREAD

**Issue by Developing-Developer2019** [irgayer/Crapper#9]
Not amazing at API's but I can't seem to run your software:
"Cannot create a 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', key length is zero.
   at Microsoft.IdentityModel.Tokens.SymmetricSecurityKey..ctor(Byte[] key)"

**Comment by yeirg** [comment]
@Developing-Developer2019 Sorry I didn't provide README. To set JWT you need to edit appsettings.json or appsettings.[Environment].json. I pushed sample and you need something like this in appsettings: 
```
"Jwt": {
    "Key": "UltraDifficultKeyDelta",
    "Audience": "http://localhost:5298",
    "Issuer": "http://localhost:5298"
  }
  ```

**Comment by yeirg** [comment]
Also, don't forget about connectionString
